---

- name: "common > Ubuntu > update apt cache"
  apt: >
    update_cache=yes
    cache_valid_time={{ my_common_cache_ttl }}
  become: yes
  become_method: sudo
  tags:
    - common-setup
    - common
    - packages-install

- name: "common > Ubuntu > install packages"
  apt: pkg={{ item }}
  with_items: "{{ my_ubuntu_common_packages }}"
  become: yes
  become_method: sudo
  tags:
    - common-setup
    - common
    - packages-install