---

- name: "common > Suse > install packages"
  zypper: >
    name={{ item }}
    state=present
  with_items: my_suse_common_packages
  become: yes
  tags:
    - common-setup
    - common
    - packages-install