---
# tasks file for common

- include: install_ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: install_suse.yml
  when: ansible_distribution == 'Suse' or ansible_distribution == 'openSUSE'